server:
  port: 8189
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false

  datasource: # datasource - откуда берем данные
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=springsecurity
    username: postgres
    password: admin
